# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: d5d19585-8dc8-4afc-ab14-cab5e8e14c41-capi-aws
  namespace: d5d19585-8dc8-4afc-ab14-cab5e8e14c41
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: d5d19585-8dc8-4afc-ab14-cab5e8e14c41-capi-aws
subjects:
- kind: ServiceAccount
  name: d5d19585-8dc8-4afc-ab14-cab5e8e14c41-capi-aws
