# Source: cluster-autoscaler/templates/rbac-for-mgmt-cluster-access.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-autoscaler-management
  namespace: d5d19585-8dc8-4afc-ab14-cab5e8e14c41
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-autoscaler-management
subjects:
- kind: ServiceAccount
  name: cluster-autoscaler
  namespace: d5d19585-8dc8-4afc-ab14-cab5e8e14c41

